import{a as p,S as L}from"./assets/vendor-CzqEfwIO.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))o(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&o(n)}).observe(document,{childList:!0,subtree:!0});function a(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(t){if(t.ep)return;t.ep=!0;const r=a(t);fetch(t.href,r)}})();const b="46842310-1eff6901abe3b896058131b9e",w="https://pixabay.com/api/";async function h(s,e=1){const a=new URLSearchParams({key:b,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:e});return(await p.get(`${w}?${a}`)).data}function v({webformatURL:s,largeImageURL:e,tags:a,likes:o,views:t,comments:r,downloads:n}){return`
    <li class="gallery-item">
      <a class="gallery-link" href="${e}">
        <img class="gallery-image" src="${s}" alt="${a}" loading="lazy" />
        <div class="image-info">
          <p class="info-item"><b>Likes:</b> ${o}</p>
          <p class="info-item"><b>Views:</b> ${t}</p>
          <p class="info-item"><b>Comments:</b> ${r}</p>
          <p class="info-item"><b>Downloads:</b> ${n}</p>
        </div>
      </a>
    </li>
  `}function g(s,e,a=!1){const o=s.map(v).join("");a?e.insertAdjacentHTML("beforeend",o):e.innerHTML=o}function l(s){const e=document.querySelector(".load-more");e&&(e.style.display=s?"block":"none")}function c(s){const e=document.querySelector(".loader");s?e.classList.add("active"):e.classList.remove("active")}function d(s){const e=document.querySelector(".toast-message");s?(e.classList.add("show"),setTimeout(()=>{e.classList.remove("show")},3e3)):e.classList.remove("show")}let u=1,y="",f=null,m=0,i=0;document.addEventListener("DOMContentLoaded",()=>{const s=document.querySelector(".search-form"),e=document.querySelector(".gallery"),a=document.querySelector(".load-more");f=new L(".gallery a",{captionsData:"alt",captionDelay:250}),s.addEventListener("submit",async o=>{o.preventDefault();const t=o.target.elements.searchQuery.value.trim();if(t){y=t,u=1,i=0;try{c(!0),l(!1),d(!1);const r=await h(t,u);if(m=r.totalHits,i=r.hits.length,r.hits.length===0){alert("Sorry, there are no images matching your search query. Please try again.");return}g(r.hits,e),f.refresh(),i>=m?d(!0):l(!0)}catch(r){console.error("Error fetching images:",r),alert("An error occurred while fetching images. Please try again.")}finally{c(!1)}}}),a.addEventListener("click",async()=>{u+=1;try{c(!0),l(!1);const o=await h(y,u);i+=o.hits.length,g(o.hits,e,!0),f.refresh();const{height:t}=e.firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"}),i>=m?d(!0):l(!0)}catch(o){console.error("Error fetching more images:",o),alert("An error occurred while fetching more images. Please try again.")}finally{c(!1)}})});
//# sourceMappingURL=index.js.map
