import{a as b,S as w,i as l}from"./assets/vendor-DtKhzRW5.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))o(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&o(i)}).observe(document,{childList:!0,subtree:!0});function a(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(t){if(t.ep)return;t.ep=!0;const r=a(t);fetch(t.href,r)}})();const v="46842310-1eff6901abe3b896058131b9e",E="https://pixabay.com/api/";async function p(s,e=1){const a=new URLSearchParams({key:v,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:e});return(await b.get(`${E}?${a}`)).data}function P({webformatURL:s,largeImageURL:e,tags:a,likes:o,views:t,comments:r,downloads:i}){return`
        <li class="gallery-item">
          <a class="gallery-link" href="${e}">
            <img class="gallery-image" src="${s}" alt="${a}" loading="lazy" />
            <div class="image-info">
              <p class="info-item"><b>Likes:</b> ${o}</p>
              <p class="info-item"><b>Views:</b> ${t}</p>
              <p class="info-item"><b>Comments:</b> ${r}</p>
              <p class="info-item"><b>Downloads:</b> ${i}</p>
            </div>
          </a>
        </li>
    `}function L(s,e,a=!1){const o=s.map(P).join("");a?e.insertAdjacentHTML("beforeend",o):e.innerHTML=o}function c(s){const e=document.querySelector(".load-more");e&&(e.style.display=s?"block":"none")}function u(s){const e=document.querySelector(".loader");s?e.classList.add("active"):e.classList.remove("active")}function d(s){const e=document.querySelector(".toast-message");s?(e.classList.add("show"),setTimeout(()=>{e.classList.remove("show")},3e3)):e.classList.remove("show")}let m=1,y="",g=null,h=0,n=0;document.addEventListener("DOMContentLoaded",()=>{const s=document.querySelector(".search-form"),e=document.querySelector(".gallery"),a=document.querySelector(".load-more");g=new w(".gallery a",{captionsData:"alt",captionDelay:250}),s.addEventListener("submit",async o=>{o.preventDefault();const t=o.target.elements.searchQuery.value.trim();if(!t){l.error({title:"Error",message:"Please enter a search query.",position:"topRight",timeout:3e3}),f();return}y=t,m=1,n=0;try{u(!0),c(!1),d(!1);const r=await p(t,m);if(h=r.totalHits,n=r.hits.length,r.hits.length===0){l.warning({title:"No Results",message:"Sorry, there are no images matching your search query. Please try again.",position:"topRight",timeout:3e3}),f();return}L(r.hits,e),g.refresh(),n>=h?d(!0):c(!0)}catch(r){console.error("Error fetching images:",r),l.error({title:"Error",message:"An error occurred while fetching images. Please try again.",position:"topRight",timeout:3e3}),f()}finally{u(!1)}}),a.addEventListener("click",async()=>{m+=1;try{u(!0),c(!1);const o=await p(y,m);n+=o.hits.length,L(o.hits,e,!0),g.refresh();const{height:t}=e.firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"}),n>=h?d(!0):c(!0)}catch(o){console.error("Error fetching more images:",o),l.error({title:"Error",message:"An error occurred while fetching more images. Please try again.",position:"topRight",timeout:3e3}),f()}finally{u(!1)}})});function f(){y="",gallery.innerHTML=""}
//# sourceMappingURL=index.js.map
